return {
  "romus204/tree-sitter-manager.nvim",
  event = "VeryLazy",
  config = function()
    require("tree-sitter-manager").setup {
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "dart",
        "diff",
        "dockerfile",
        "doxygen",
        "editorconfig",
        "elixir",
        "fish",
        "glsl",
        "go",
        "gomod",
        "html",
        "javascript",
        "json",
        "julia",
        "kdl",
        "latex",
        "linkerscript",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "meson",
        "nim",
        "ninja",
        "nix",
        "pioasm",
        "python",
        "re2c",
        "regex",
        "ruby",
        "rust",
        "slint",
        "solidity",
        "sql",
        "svelte",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
        "zig",
      },
      auto_install = true,
      border = "rounded",
    }
  end,
}
