return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  branch = "master",
  dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
  lazy = false,
  main = "nvim-treesitter.configs",
  opts = {
    indent = { enable = true },
    highlight = { enable = true },
    ensure_installed = {
      "asm",
      "bash",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "dart",
      "diff",
      "dockerfile",
      "doxygen",
      "editorconfig",
      "elixir",
      "fish",
      "glsl",
      "go",
      "gomod",
      "html",
      "javascript",
      "json",
      "julia",
      "kdl",
      "latex",
      "linkerscript",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "nim",
      "ninja",
      "nix",
      "pioasm",
      "python",
      "re2c",
      "regex",
      "ruby",
      "rust",
      "slint",
      "solidity",
      "sql",
      "svelte",
      "toml",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    },
  },
}
